package com.anoki.simpleBoard.models;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;


/**
 * An entity User composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 */
@Entity
@Table(name = "posts")
public class Post {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private int id_post;
  
  @NotNull
  private User id_user;
  
  @NotNull
  private String text;

  
  private String hidden;
  
  
  private String hidden_by;

  
  private String deleted;
  
  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public Post() {}
  
  public Post(User id_user, String text) {
    this.id_user =  id_user;
    this.text = text;
  }

  
  // Getter and setter methods

  public Post(int id_post, User id_user, String text, String hidden, String hidden_BY, String deleted) {
	this.id_post = id_post;
	this.id_user = id_user;
	this.text = text;
	this.hidden = hidden;
	this.hidden_by = hidden_by;
	this.deleted = deleted;
}


public int getId() {
    return id_post;
  }
  

  public User getIdUser() {
	return id_user;
  }
  
  public String gettext() {
	return text;
  }

  public void settext(String text) {
    this.text = text;
  }
  

  public String gethidden() {
    return hidden;
  }
  
  public void sethidden(String hidden) {
	this.hidden = hidden;
  }
  
  public String gethiddenBy() {
    return hidden_by;
  }
  
  public void sethiddenBy(String hiddenBy) {
	this.hidden_by = hiddenBy;
  }
  
  public String getdeleted() {
	return deleted;
  }
  
  public void setdeleted(String deleted) {
	this.deleted = deleted;
  }
  
  
} // class Post


