package com.anoki.simpleBoard.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * An entity User composed by three fields (id, email, name).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the name for the table in the db.
 */
@Entity
@Table(name = "users")
public class User {

  // ------------------------
  // PRIVATE FIELDS
  // ------------------------
  
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private int idUser;
  
  @NotNull
  private String username;
  
  @NotNull
  private String name;

  @NotNull
  private String email;
  
  @NotNull
  private String password;

  @NotNull
  private String userType;
  
  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public User() {}

  // Getter and setter methods

  public int getId() {
    return idUser;
  }
  
  public String getName() {
	return name;
  }

  public void setName(String name) {
    this.name = name;
  }
  

  public String getEmail() {
    return email;
  }
  
  public void setEmail(String email) {
    this.email = email;
  }
  

  public void setPassword(String password) {
    this.password = password;
  }
  
  public void setUserType(String userType) {
	this.userType = userType;
  }
  
  public String getUserType(String userType) {
	    return userType;
  }
  
} // class User